### ISSUE TITLE
หน้าเรียกคิวเข้าห้องตรวจแบบกลุ่ม ให้สามารถระบุ default ช่องรับบริการได้

### ISSUE THREAD

**Issue by dixonsatit** [mophos/queue-docker#12]
เนื่องจากคอมส่วนใหญ่ที่ให้บริการยังใช้ Windows XP ไม่สามารถติดตั้งและใช้งานตัว QueueCaller exe ได้ จึงอยากขอปรับหน้าจอเรียกคิวเข้าห้องตรวจ ( แบบกลุ่ม ) ให้สามารถระบุ default ช่องให้บริการได้ โดยให้สามารถตั้งค่า default ได้ว่าจะให้เรียกคิวตามช่องบริการหรือใช้วิธีกดเรียกแล้วเลือกช่องบริการก็ได้ครับ

- [ ] เพิ่มตัวตั้งค่าให้สามารถเลือกได้ว่าจะใช้ช่องบริการตาม default หรือให้เลือกเองในตอนเรียกคิว
- [x] ในกรณีที่ตั้งค่าใช้ช่องบริการตาม default หน้าจอเรียกคิวแบบกลุ่มให้เพิ่มตัวเลือกว่าจะออกตามช่องบริการไหน

![screen shot 2562-03-08 at 12 34 41](https://user-images.githubusercontent.com/1027274/54009899-42edd880-419f-11e9-800c-46d3c36db49f.png)

**Comment by siteslave** [comment]
![Screen Shot 2562-03-11 at 15 19 21](https://user-images.githubusercontent.com/526890/54110469-0e368700-4414-11e9-9e5b-bd955116d09c.png)

**Comment by dixonsatit** [comment]
@siteslave  ได้ๆ ครับ ไม่มีตั้งค่าก็ได้ขอแค่ให้สามารถเลือกได้ครับ
