### ISSUE TITLE
การออกหมายเลขคิวให้ออกเลขตาม clinic และ ประเภทผู้ป่วย

### ISSUE THREAD

**Issue by dixonsatit** [mophos/queue-docker#13]
แต่ถ้าเป็นรพ.ที่มีการรับบริการมากๆ อย่างเช่น คลินิก A มีผุ้ป่วย 3 ประเภท เช่น ปกติ, vip, เร่งด่วน  ถ้าแบบเดิม
ก็จะเป็น

1 = ทั่วไป
2 = เร่งด่วน
3 = VIP

- A1 001
- A1 002
- A2 003
- A3 004
ถ้าพยาบาลจะเรียก `A2 003` เร่งด่วนก่อนเวลาเรียก คนอื่นๆ ก็จะสงสัย ว่าทำไม `A2 003` เข้าไปก่อน อะไรแบบนี้ครับ  แต่ถ้าแยกไปเลยก็จะเข้าใจว่าคนละอันจะได้ไม่มีคำถาม

ถ้าเรียงตามประเภทผู้ป่วย
- A1 001
- A1 002
- A2 001
- A3 001
สมมุติว่าเรียก `A2 001` ก่อน `A1 001` ก็จะไม่มีปัญหาครับ

อาจจะเพิ่มเป็น option ให้กำหนดค่าก็ได้ครับว่าที่ใหนจะให้ออกคิวตามประเภทผู้ป่วยบ้าง

**Comment by siteslave** [comment]
https://github.com/mophos/queue-web/pull/52
https://github.com/mophos/queue-api/pull/47

![Screen Shot 2562-03-12 at 10 01 26](https://user-images.githubusercontent.com/526890/54171907-ad0fc180-44ae-11e9-8afc-8fb932376845.png)
![Screen Shot 2562-03-12 at 09 59 19](https://user-images.githubusercontent.com/526890/54171918-b305a280-44ae-11e9-9499-b6e4528af8c9.png)
![Screen Shot 2562-03-12 at 09 59 27](https://user-images.githubusercontent.com/526890/54171919-b305a280-44ae-11e9-8070-0787a0c79b79.png)
