### ISSUE TITLE
การแสดงผลที่ tablet ขนาด 7 นิ้ว ไม่ครบ

### ISSUE THREAD

**Issue by Teakongnoo** [mophos/queue-docker#15]
การแสดงผลที่ tablet ขนาด 7 นิ้ว ไม่แสดง ต้องเรียกผ่าน  URL เท่านั้น

**Comment by siteslave** [comment]
แก้ไขเรียบร้อยครับ https://github.com/mophos/queue-web/commit/c30d3f735feac1af813b47dcabd4add872a3c87d
