### ISSUE TITLE
หน้าจอเรียกคิวแบบกลุ่ม ช่องที่แสดงคิวกำลังเรียกแสดงข้อมูลไม่ตรงกัน

### ISSUE THREAD

**Issue by dixonsatit** [mophos/queue-docker#17]
กรณีที่เราเรียกคิวทีล่ะหลายๆ รายการพร้อมกันอาจจะเป็นทีล่ะ 2,3,5 ก็ได้ แต่ช่องที่แสดง `คิวที่กำลังเรียก` แสดงรายการที่กำลังเรียกไม่เหมือนกันถ้าเปิดใช้งานหลายๆ เครื่องพร้อมกัน ของผมใช้ 4 เครื่องพร้อมกัน
สมมุติว่า
- เครื่องที่ 1 เรียกที่ช่องบริการ 23, เรียกคิวที่ 100-105 หน้าจอช่อง  `คิวที่กำลังเรียก`  จะแสดงว่ามี 5 คิวกำลังถูกเรียก
- เครื่องที่ 2 ที่กำลังเรียกเหมือนกันที่ช่องบิรการ 24 จะเห็นข้อมูลช่อง  `คิวที่กำลังเรียก` แค่รายการสุดท้ายครับ ไม่เห็นเหมือนกันกับเครื่องแรกที่เป็นคนเรียกคิว
![Screen Shot 2562-03-14 at 14 46 20](https://user-images.githubusercontent.com/1027274/54339921-c5c3d700-4668-11e9-8052-527699efd9f0.png)

**Comment by siteslave** [comment]
@beerIT15kmutnb ช่วยดูให้หน่อยครับ
