### ISSUE TITLE
หน้าจอเรียกคิวแบบกลุ่ม ขอเพิ่มช่อง filter ให้เรียกคิวเฉพาะประเภทผู้ป่วยที่เลือก

### ISSUE THREAD

**Issue by dixonsatit** [mophos/queue-docker#19]
ถ้าหากตั้งค่าให้ออกคิวตามประเภทผู้ป่วย หลังจากที่ผู้ป่วยได้รับบัตรคิวตามประเภทแล้ว ก็จะได้ลำดับดังนี้ 
- D1 001
- D1 002
- D1 003
- D2 001
- D1 004
- D2 002

เมือผุ้ป่วยได้รับคิวแล้ว ในแต่ละช่องบริการส่วนใหญ่จะเรียกคิวแค่ประเภทเดียวเช่น
ช่องบริการที่ 22 เรียกเฉพาะ ประเภททั่วไปคือ
- D1 001
- D1 002
- D1 003

ช่องบริการที่ 23 เรียกเฉพาะ ประเภทผู้ป่วยช่องทางพิเศษ
- D2 001
- D2 002

อยากให้เพิ่มช่อง filter ช่องรายการคิวรอเรียก ปกติเราเลือกช่องบริการแล้วให้เลือกแสดงตามประเภทผู้ป่วยที่ต้องการด้วย ถ้าไม่เลือกก็ให้แสดงทั้งหมดปกติครับ

- [x] กรณีไม่เลือกให้แสดงทั้งหมดตามปกติ
- [x] กรณีเลือกประเภทผุ้ป่วยให้แสดงเฉพาะรายการคิวของประเภทนั้นๆ

![Screen Shot 2562-03-14 at 15 25 11](https://user-images.githubusercontent.com/1027274/54342256-931cdd00-466e-11e9-8886-905f23df7ab6.png)

**Comment by siteslave** [comment]
![Screen Shot 2562-03-16 at 21 58 48](https://user-images.githubusercontent.com/526890/54477116-4801f600-4837-11e9-8c86-a963b5f338e0.png)

https://github.com/mophos/queue-web/commit/345b8d6a1a670604374bc46ea3ec9046702680e8
