### ISSUE TITLE
ขอเพิ่มปุ่มซ่อนแสดง sidebar menu ด้านซ้ายครับ

### ISSUE THREAD

**Issue by dixonsatit** [mophos/queue-docker#21]
พอดีเวลาเรียกคิวต่างๆ หน้าจอมันดูแคบอยากให้มันสามารถซ่อนเมนูไว้ได้ครับ จะได้ใช้งานสะดวกๆ เต็มที่ อยากได้ปุ่มที่กดแล้วซ่อนแสดงเมนูด้ายซ้ายครับ

![Screen Shot 2562-03-14 at 23 21 56](https://user-images.githubusercontent.com/1027274/54374840-8c17be00-46b2-11e9-9abf-fdd694b1b9bb.png)

**Comment by siteslave** [comment]
เดี๋ยวปรับให้ครับ

**Comment by siteslave** [comment]
@dixonsatit คลิกที่โลโก้ของ Q4U นะครับ เพื่อ Toggle menu
