### ISSUE TITLE
ตัดข้อความบัตรคิว

### ISSUE THREAD

**Issue by Teakongnoo** [mophos/queue-docker#23]
￼￼ต้องการเอาข้อความคำว่า ซักประวัติออก 
<img width="313" alt="Capture" src="https://user-images.githubusercontent.com/40262506/54414654-6d560d80-472c-11e9-9e83-918af38ae5bc.PNG">

**Comment by siteslave** [comment]
@Teakongnoo จะเพิ่มให้เป็นการตั้งค่าให้นะครับ ว่าจะให้มีหรือไม่มีคิวซักประวัติ

**Comment by siteslave** [comment]
ปรับแก้ใน printer gateway แล้ว
