### ISSUE TITLE
เมื่อ ลงโปรแกรม แบบใช้ Source Code แล้วติดดังภาพ

### ISSUE THREAD

**Issue by Teakongnoo** [mophos/queue-docker#32]
![image](https://user-images.githubusercontent.com/40262506/56492750-fa079e80-6516-11e9-947f-77ac506a5a95.png)

ขอวิธีแก้ไขครับ

**Comment by siteslave** [comment]
ตัวนี้แค่ warning ครับ สามารถทำงานต่อได้ครับ
